### ISSUE TITLE
fix frisquet-ERS-command-transceiver.ino

### ISSUE THREAD

**Issue by chouteaup** [ChristopheHD/frisquet-arduino#6]
Il y a un bug dans frisquet-ERS-command-transceiver.ino

La boucle principale qui envoie la commande en appelant conversion doit itérer sur la variable globale num_byte et non sur une variable local i 

Cela entraine une erreur au niveau du bitstuffing a cause de la condition 
```
    if (num_byte >= 4 && num_byte <= 14) {
```

il faut donc remplacer 
```
    for (int i = 1; i <= 16; i++) { // boucle de 16 bytes
      conversion(message[i]);
```
par 
```
    for (num_byte = 1; num_byte <= 16; num_byte++) { // boucle de 16 bytes
      conversion(message[num_byte]); 
```

**Comment by ChristopheHD** [comment]
Correction intégrée, merci pour la remarque.
